/** Default master colour list for Rugs Bhadohi (name + hex). */
export const DEFAULT_COLORS: ReadonlyArray<{ name: string; hex: string }> = [
  { name: "White", hex: "#FFFFFF" },
  { name: "Off White", hex: "#F8F8F2" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Cream", hex: "#FFFDD0" },
  { name: "Linen", hex: "#FAF0E6" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Sand", hex: "#C2B280" },
  { name: "Natural", hex: "#D8C3A5" },
  { name: "Taupe", hex: "#B38B6D" },
  { name: "Greige", hex: "#B7B09C" },
  { name: "Camel", hex: "#C19A6B" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Khaki", hex: "#C3B091" },
  { name: "Brown", hex: "#8B5A2B" },
  { name: "Chocolate", hex: "#5D4037" },
  { name: "Coffee", hex: "#6F4E37" },
  { name: "Mocha", hex: "#7B5E57" },
  { name: "Walnut", hex: "#773F1A" },
  { name: "Chestnut", hex: "#954535" },
  { name: "Grey", hex: "#808080" },
  { name: "Light Grey", hex: "#D3D3D3" },
  { name: "Medium Grey", hex: "#A9A9A9" },
  { name: "Dark Grey", hex: "#555555" },
  { name: "Charcoal", hex: "#36454F" },
  { name: "Graphite", hex: "#41424C" },
  { name: "Black", hex: "#000000" },
  { name: "Blue", hex: "#1E88E5" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Navy", hex: "#1A237E" },
  { name: "Indigo", hex: "#3F51B5" },
  { name: "Denim", hex: "#1565C0" },
  { name: "Slate Blue", hex: "#6A7BA2" },
  { name: "Teal", hex: "#008080" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Aqua", hex: "#00BCD4" },
  { name: "Green", hex: "#2E7D32" },
  { name: "Sage", hex: "#9CAF88" },
  { name: "Olive", hex: "#808000" },
  { name: "Moss", hex: "#8A9A5B" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Emerald", hex: "#50C878" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Yellow", hex: "#FFD54F" },
  { name: "Mustard", hex: "#D4A017" },
  { name: "Gold", hex: "#D4AF37" },
  { name: "Ochre", hex: "#CC7722" },
  { name: "Orange", hex: "#FB8C00" },
  { name: "Burnt Orange", hex: "#CC5500" },
  { name: "Terracotta", hex: "#E2725B" },
  { name: "Rust", hex: "#B7410E" },
  { name: "Red", hex: "#C62828" },
  { name: "Brick Red", hex: "#B22222" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Wine", hex: "#722F37" },
  { name: "Maroon", hex: "#800000" },
  { name: "Pink", hex: "#F48FB1" },
  { name: "Blush", hex: "#F9C6C9" },
  { name: "Dusty Rose", hex: "#DCAE96" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Peach", hex: "#FFDAB9" },
  { name: "Purple", hex: "#7E57C2" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "Plum", hex: "#8E4585" },
  { name: "Lilac", hex: "#C8A2C8" },
  { name: "Violet", hex: "#8F00FF" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Metallic Gold", hex: "#D4AF37" },
  { name: "Metallic Silver", hex: "#BCC6CC" },
  { name: "Copper", hex: "#B87333" },
  { name: "Multicolor", hex: "#999999" },
];
